'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace Huggle
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
    Public Module Resources

        Private resourceMan As Global.System.Resources.ResourceManager

        Private resourceCulture As Global.System.Globalization.CultureInfo

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(ByVal value As Global.System.Globalization.CultureInfo)
                resourceCulture = Value
            End Set
        End Property

        Public ReadOnly Property abuse_filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abuse_filter", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to &lt;div style=&quot;font-family: sans-serif&quot;&gt;
        '''{0}
        '''&lt;/div&gt;.
        '''</summary>
        Public ReadOnly Property BasicHtmlPage() As String
            Get
                Return ResourceManager.GetString("BasicHtmlPage", resourceCulture)
            End Get
        End Property

        Public ReadOnly Property blob_anon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_anon", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_anon_filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_anon_filter", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_blank", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_blanked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_blanked", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_blocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_blocked", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_blocknote() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_blocknote", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_bot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_bot", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_filter", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_ignored() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_ignored", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_ignored_assisted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_ignored_assisted", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_log() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_log", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_log_block() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_log_block", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_log_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_log_delete", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_log_newuser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_log_newuser", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_log_protect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_log_protect", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_log_unblock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_log_unblock", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_log_undelete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_log_undelete", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_log_unprotect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_log_unprotect", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_me() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_me", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_message() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_message", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_new", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_none() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_none", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_none_assisted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_none_assisted", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_none_filter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_none_filter", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_redirect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_redirect", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_replaced() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_replaced", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_report", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_reported() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_reported", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_revert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_revert", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_reverted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_reverted", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_tag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_tag", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_warn_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warn_1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_warn_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warn_2", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_warn_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warn_3", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_warn_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warn_4", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warning", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_warning_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warning_1", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_warning_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warning_2", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_warning_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warning_3", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property blob_warning_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blob_warning_4", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property data_chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_chart", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property data_html() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_html", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property data_image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_image", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property data_table() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_table", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property data_text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_text", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property data_webpage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_webpage", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property data_wikitext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_wikitext", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to userrights-title:                User rights for {0}
        '''
        '''changepassword-error:            The old password was incorrect, or there was an error submitting the request
        '''
        '''time-day:                        {0} day
        '''time-day-s:                      {0} days
        '''time-minute:                     {0} minute
        '''time-minute-s:                   {0} minutes
        '''time-hour:                       {0} hour
        '''time-hour-s:                     {0} hours
        '''time-second:                     {0} second
        '''time-second-s:                   {0 [rest of string was truncated]&quot;;.
        '''</summary>
        Public ReadOnly Property en() As String
            Get
                Return ResourceManager.GetString("en", resourceCulture)
            End Get
        End Property

        Public ReadOnly Property error_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error_icon", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property family_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("family_icon", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property globaluser_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("globaluser_icon", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property HuggleLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HuggleLogo", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property Icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon", resourceCulture)
                Return CType(obj, System.Drawing.Icon)
            End Get
        End Property

        Public ReadOnly Property mediawiki_extension() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mediawiki_extension", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property mediawiki_gadget() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mediawiki_gadget", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property mediawiki_wiki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mediawiki_wiki", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to 1movedto2
        '''1movedto2_redir
        '''blocklogentry
        '''deletedarticle
        '''modifiedarticleprotection
        '''newuserlog-create-entry
        '''newuserlog-create2-entry
        '''overwroteimage
        '''patrol-log-line
        '''protectedarticle
        '''reblock-logentry
        '''renameuser-log
        '''renameuserlogentry
        '''review-logentry-app
        '''rightslogentry
        '''unblocklogentry
        '''undeletedarticle
        '''unprotectedarticle
        '''uploadedimage.
        '''</summary>
        Public ReadOnly Property messages() As String
            Get
                Return ResourceManager.GetString("messages", resourceCulture)
            End Get
        End Property

        Public ReadOnly Property mini_no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mini_no", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property mini_question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mini_question", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property mini_yes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mini_yes", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property powered_by_mediawiki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powered_by_mediawiki", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property

        Public ReadOnly Property user_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user_icon", resourceCulture)
                Return CType(obj, System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace